/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.kokkiemouse.minecraft_decompiler_official;

import io.github.kokkiemouse.minecraft_decompiler_official.lib.Get_OS;
import io.github.kokkiemouse.minecraft_decompiler_official.lib.MCDecompiler;

import java.io.IOException;
import java.net.URL;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        MCDecompiler mcd=new MCDecompiler();
        mcd.set_CLIENT_OR_SERVER(MCDecompiler.MCJAR_TYPE.CLIENT);
        mcd.set_decompile_version("1.16.1");
        mcd.get_version_manifest();
        mcd.get_mappings();
        mcd.convert_mappings();
        mcd.get_minecraft_jar();
    }
}
