/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.kokkiemouse.minecraft_decompiler_official;

import io.github.kokkiemouse.minecraft_decompiler_official.lib.Get_OS;
import io.github.kokkiemouse.minecraft_decompiler_official.lib.MCDecompiler;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.println(MCDecompiler.get_minecraft_path());
    }
}
